### ISSUE TITLE
Clarifications needed in the requirements part

### ISSUE THREAD

**Issue by LambolezPaul** [openglbook/openglbook.com#46]
Hello, 

The requirements part of your preface clearly need to be enhanced for various reasons. 
First, it is currently embedded within a quite descriptive (yet interesting) chapter, the subject of which mainly is OpenGL history. I cannot see any logical reason for current requirements regarding this very book to be there. 
Another issue lies in its size: it is far too short, at least for beginners. The software requirement should be split based on OS and provide detailed installation information (or, at least, links to reliable tutorials/walkthroughs). I'm especially thinking about FreeGlut/GLEW for the OS X plateforme. Granted, a good google search could be enough, but only for an experienced user. Beginners, be it regarding programming as a whole or regarding their plateforme (i.e. OS), might get lost in the installation process (once more, especially regarding 3rd party libraries) and get the feeling that OpenGL is simply too complicated to work with. This is a pity. Especially looking at how talented you are at giving crystal clear explanations in the others chapters.
Finally, on a more technical aspect, openGL 4.0 support is not restricted to GPUs, for instance most recent iGPs support it. It would be convenient to have a link to a list of all supported devices (providing it exists) or a link to each vendor website to ensure up-to-date information. 

Those thoughts come mainly from my experience trying to set everything up on OS X. The Windows installation is far easier (but I might not be as neutral as it's the OS I use the most) and the linux one should be a walk in the park thanks to the packet installer. Yet, making this process as simple as possible would do nothing but help in making it as accessible as possible.
Your work clearly deserves it.

**Comment by EddyLuten** [comment]
Hi @LambolezPaul, thanks for the suggestions.

I may move the requirements into a separate blog post or something away from the preface, which I agree, is not required reading.

As for OS-specifics, those may be added in the future as blog posts or appendices.

On the technical note, yes, finally some integrated GPUs finally support GL 4.x. At the time of initial writing, which would be mid-2010, they did not, which is why the text still mentions this.

All of these things - and many more - will be addressed once I have some time to dedicate to this project.

I appreciate you filing this ticket and will keep it open until I can work on it.
